// Mock Wails bindings for development — v2.1
// In production these are auto-generated by Wails from Go methods

const delay = (ms = 300) => new Promise(r => setTimeout(r, ms))

function paged(items, page, pageSize) {
  const start = (page - 1) * pageSize
  return { items: items.slice(start, start + pageSize), total: items.length, page, page_size: pageSize }
}

// ── Mock data ──────────────────────────────────────────────────────────────

const MOCK_PROFILES = [
  { seq: 1, profile_id: '9023104163bd47ffa784', display_name: '账号A', douyin_uid: '111001', nickname: '@张三', cookie_status: 'valid', cookie_updated_at: '2026-03-23T08:00:00Z', test_passed: true, enabled: true, daily_dm_sent: 45, daily_dm_limit: 100, consecutive_failures: 0 },
  { seq: 2, profile_id: '8a12bc45def678901234', display_name: '账号B', douyin_uid: '111002', nickname: '@李四', cookie_status: 'valid', cookie_updated_at: '2026-03-23T07:30:00Z', test_passed: true, enabled: true, daily_dm_sent: 23, daily_dm_limit: 100, consecutive_failures: 0 },
  { seq: 3, profile_id: '7f89ab01234567890abc', display_name: '账号C', douyin_uid: '111003', nickname: '@王五', cookie_status: 'expired', cookie_updated_at: '2026-03-22T10:00:00Z', test_passed: false, enabled: false, daily_dm_sent: 0, daily_dm_limit: 100, consecutive_failures: 3 },
]

const MOCK_VIDEOS = [
  { video_id: '7615062955545169201', title: '减肥干货大合集#健康', author_nickname: '@健身博主A', cover_url: '', like_count: 12800, comment_count: 3240, status: 'active', total_comments_collected: 890, last_check_at: '2026-03-23T10:30:00Z', added_at: '2026-03-23T09:00:00Z', source_keyword: '减肥', bound_profile_id: '9023104163bd47ffa784', bound_seq: 1 },
  { video_id: '7615062955545169202', title: '川西旅行攻略分享', author_nickname: '@旅行达人B', cover_url: '', like_count: 6100, comment_count: 980, status: 'active', total_comments_collected: 320, last_check_at: '2026-03-23T10:25:00Z', added_at: '2026-03-23T09:10:00Z', source_keyword: '川西', bound_profile_id: '8a12bc45def678901234', bound_seq: 2 },
  { video_id: '7615062955545169203', title: '这款产品真的yyds', author_nickname: '@种草博主C', cover_url: '', like_count: 45000, comment_count: 8900, status: 'paused', total_comments_collected: 2100, last_check_at: '2026-03-23T10:00:00Z', added_at: '2026-03-23T08:30:00Z', source_keyword: '产品推荐', bound_profile_id: '9023104163bd47ffa784', bound_seq: 1 },
  { video_id: '7615062955545169204', title: '旅游必备好物分享', author_nickname: '@生活博主D', cover_url: '', like_count: 8200, comment_count: 1540, status: 'active', total_comments_collected: 430, last_check_at: '2026-03-23T10:20:00Z', added_at: '2026-03-23T09:20:00Z', source_keyword: '好物', bound_profile_id: '8a12bc45def678901234', bound_seq: 2 },
  { video_id: '7615062955545169205', title: '美食探店合集', author_nickname: '@美食博主E', cover_url: '', like_count: 32000, comment_count: 6700, status: 'active', total_comments_collected: 1200, last_check_at: '2026-03-23T10:15:00Z', added_at: '2026-03-23T08:00:00Z', source_keyword: '美食', bound_profile_id: '9023104163bd47ffa784', bound_seq: 1 },
]

const MOCK_COMMENTS = Array.from({ length: 52 }, (_, i) => ({
  comment_id: `cmt_${i + 1}`,
  video_id: '7615062955545169201',
  level: i % 5 === 0 ? 2 : 1,
  uid: `uid_${1000 + i}`,
  sec_uid: `sec_uid_${i}`,
  nickname: `用户${i + 1}`,
  content: ['这个多少钱？', '怎么买', '有链接吗', '怎么联系你', '在哪里可以入手', '哈哈哈好看', '支持！', '求推荐', '价格是多少', '想买一个'][i % 10],
  region: ['广东', '北京', '上海', '浙江', '四川'][i % 5],
  like_count: Math.floor(Math.random() * 100),
  created_at: Math.floor(Date.now() / 1000) - i * 300,
  dm_status: ['pending_review', 'approved', 'sent', 'failed', 'skip'][i % 5],
}))

const MOCK_DM_KEYWORDS = [
  { id: 'kw1', keyword: '怎么买', match_type: 'fuzzy', category: 'purchase_intent', enabled: true, hit_count: 128, created_at: '2026-03-23T09:00:00Z' },
  { id: 'kw2', keyword: '多少钱', match_type: 'fuzzy', category: 'price_inquiry', enabled: true, hit_count: 95, created_at: '2026-03-23T09:00:00Z' },
  { id: 'kw3', keyword: '怎么联系', match_type: 'exact', category: 'contact_request', enabled: true, hit_count: 67, created_at: '2026-03-23T09:00:00Z' },
  { id: 'kw4', keyword: '购买意向词库', match_type: 'semantic', category: 'purchase_intent', enabled: true, hit_count: 210, created_at: '2026-03-23T09:00:00Z' },
  { id: 'kw5', keyword: '在哪买', match_type: 'fuzzy', category: 'channel_source', enabled: false, hit_count: 34, created_at: '2026-03-23T09:00:00Z' },
]

const MOCK_TASKS_REVIEW = Array.from({ length: 23 }, (_, i) => ({
  task_id: `task_review_${i}`,
  target_uid: `uid_${2000 + i}`,
  target_nickname: `用户${i + 100}`,
  target_sec_uid: `sec_${i}`,
  source_video_id: '7615062955545169201',
  source_video_title: '减肥干货大合集#健康',
  source_comment_content: ['怎么买这个', '多少钱一盒', '有联系方式吗', '哪里可以入手', '想买'][i % 5],
  trigger_keyword: ['怎么买', '多少钱', '怎么联系', '购买意向词库', '在哪买'][i % 5],
  message_preview: `你好 用户${i + 100}，看到你的评论很感兴趣，我这边有相关资源想和你分享～`,
  executed_profile_id: '',
  executed_seq: 0,
  status: 'pending_review',
  error_msg: '',
  retry_count: 0,
  created_at: new Date(Date.now() - i * 600000).toISOString(),
  sent_at: '',
}))

const MOCK_TASKS_QUEUE = Array.from({ length: 38 }, (_, i) => ({
  task_id: `task_q_${i}`,
  target_uid: `uid_${3000 + i}`,
  target_nickname: `用户${i + 200}`,
  target_sec_uid: `sec_q_${i}`,
  source_video_id: '7615062955545169201',
  source_video_title: '减肥干货大合集#健康',
  source_comment_content: '怎么买这个',
  trigger_keyword: '怎么买',
  message_preview: `你好 用户${i + 200}，看到你的评论很感兴趣...`,
  executed_profile_id: i % 2 === 0 ? '9023104163bd47ffa784' : '8a12bc45def678901234',
  executed_seq: i % 2 === 0 ? 1 : 2,
  status: ['approved', 'sent', 'sent', 'failed', 'sending'][i % 5],
  error_msg: i % 5 === 3 ? '接口超时' : '',
  retry_count: i % 5 === 3 ? 1 : 0,
  created_at: new Date(Date.now() - i * 900000).toISOString(),
  sent_at: i % 5 !== 0 ? new Date(Date.now() - i * 600000).toISOString() : '',
}))

const MOCK_DM_SEND_LOGS = Array.from({ length: 58 }, (_, i) => ({
  id: `log_dm_${i}`,
  sent_at: new Date(Date.now() - i * 720000).toISOString(),
  window_seq: (i % 2) + 1,
  profile_id: i % 2 === 0 ? '9023104163bd47ffa784' : '8a12bc45def678901234',
  sender_nickname: i % 2 === 0 ? '@张三' : '@李四',
  target_uid: `uid_${4000 + i}`,
  target_nickname: `用户${i + 300}`,
  source_video_id: '7615062955545169201',
  source_video_title: '减肥干货大合集#健康',
  comment_content: '怎么买这个',
  trigger_keyword: i % 4 === 3 ? '全量模式' : '怎么买',
  message_content: `你好 用户${i + 300}，看到你对这个感兴趣，我这边有相关资源想和你分享～`,
  status: i % 7 === 0 ? 'failed' : i % 11 === 0 ? 'rate_limited' : 'sent',
  error_msg: i % 7 === 0 ? '接口限流' : '',
}))

const MOCK_COLLECT_HISTORY = Array.from({ length: 22 }, (_, i) => ({
  id: `history_${i}`,
  keyword_id: 'kw_collect_1',
  keyword: ['减肥', '川西', '好物推荐', '旅行攻略'][i % 4],
  started_at: new Date(Date.now() - i * 3600000).toISOString(),
  finished_at: new Date(Date.now() - i * 3600000 + 5000).toISOString(),
  duration_sec: 4 + i % 8,
  collected: 10 + i % 20,
  filtered_out: i % 5,
  added: 8 + i % 12,
  status: i % 8 === 0 ? 'failed' : 'success',
  error_msg: i % 8 === 0 ? 'Cookie 失效' : '',
}))

const MOCK_SEARCH_RESULTS = Array.from({ length: 28 }, (_, i) => ({
  video_id: `search_${i}`,
  title: `搜索结果视频${i + 1} #话题${i % 4}`,
  author_nickname: `博主${i + 1}`,
  cover_url: '',
  like_count: 1000 + i * 500,
  comment_count: 100 + i * 50,
  published_at: new Date(Date.now() - i * 86400000).toISOString(),
  source_keyword: '减肥',
  already_added: i % 5 === 0,
}))

const MOCK_SYSTEM_LOGS = Array.from({ length: 67 }, (_, i) => ({
  id: `syslog_${i}`,
  level: ['INFO', 'INFO', 'INFO', 'WARN', 'ERROR'][i % 5],
  message: ['监控引擎启动成功', '评论采集完成：新增 12 条', '私信引擎运行中', 'Cookie 即将过期，请刷新', 'API 请求超时，已重试'][i % 5],
  created_at: new Date(Date.now() - i * 120000).toISOString(),
}))

// ── 评论监控 ───────────────────────────────────────────────────────────────

export async function GetVideos(page = 1, pageSize = 8) {
  await delay()
  return paged(MOCK_VIDEOS, page, pageSize)
}

export async function AddVideo(url, profileId) {
  await delay(500)
  return null
}

export async function DeleteVideo(videoId) {
  await delay(300)
  return null
}

export async function StartMonitor() { await delay(); return null }
export async function StopMonitor() { await delay(); return null }

export async function GetMonitorStatus() {
  return { running: true, current_round: 12, new_comments_this_round: 3, total_comments: 1284 }
}

export async function GetComments(videoId, page = 1, pageSize = 11) {
  await delay()
  return paged(MOCK_COMMENTS, page, pageSize)
}

export async function ExportVideos(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/videos_export.${format}`
}

export async function ExportComments(videoId, format) {
  await delay(800)
  return `C:/Users/43841/Downloads/comments_export.${format}`
}

// ── 视频采集 ───────────────────────────────────────────────────────────────

export async function SearchVideos(keyword, sortType, publishTime, duration, count) {
  await delay(1000)
  return MOCK_SEARCH_RESULTS.slice(0, count || 20)
}

export async function StartAutoCollect() { await delay(); return null }
export async function StopAutoCollect() { await delay(); return null }

export async function GetKeywords() {
  await delay()
  return [
    { id: 'kw_collect_1', keyword: '减肥', enabled: true, priority: 5, search_time_range: 'week', count_per_run: 10, stats: { total_collected: 190, total_monitored: 20 }, last_run_at: '2026-03-23T10:00:00Z', created_at: '2026-03-01T00:00:00Z' },
    { id: 'kw_collect_2', keyword: '川西旅行', enabled: true, priority: 3, search_time_range: 'all', count_per_run: 20, stats: { total_collected: 80, total_monitored: 12 }, last_run_at: '2026-03-23T09:30:00Z', created_at: '2026-03-05T00:00:00Z' },
    { id: 'kw_collect_3', keyword: '好物推荐', enabled: false, priority: 2, search_time_range: 'day', count_per_run: 15, stats: { total_collected: 45, total_monitored: 8 }, last_run_at: '2026-03-22T20:00:00Z', created_at: '2026-03-10T00:00:00Z' },
  ]
}

export async function AddKeyword(config) { await delay(); return null }
export async function UpdateKeyword(config) { await delay(); return null }
export async function DeleteKeyword(id) { await delay(); return null }

export async function GetCollectHistory(page = 1, pageSize = 8) {
  await delay()
  return paged(MOCK_COLLECT_HISTORY, page, pageSize)
}

export async function GetAutoCollectStatus() {
  return { running: false, next_collect_in_sec: 180, current_round_videos: 0, total_monitored: 5 }
}

export async function ExportCollectHistory(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/collect_history.${format}`
}

// ── 私信账号 ───────────────────────────────────────────────────────────────

export async function GetAccounts(page = 1, pageSize = 6) {
  await delay()
  return paged(MOCK_PROFILES, page, pageSize)
}

export async function AddAccount(profileId) { await delay(500); return null }
export async function DeleteAccount(profileId) { await delay(); return null }
export async function ExtractAccountInfo(profileId) { await delay(1500); return null }
export async function TestSendDM(profileId, targetUID) { await delay(2000); return null }

export async function LoginBitBrowserWindow(profileId) {
  await delay(500)
  return { ws: `ws://127.0.0.1:9222/${profileId}` }
}

export async function ExportAccounts(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/accounts.${format}`
}

export async function GetStartupCheckResult() {
  await delay(1200)
  return MOCK_PROFILES.map(p => ({
    seq: p.seq,
    profile_id: p.profile_id,
    nickname: p.nickname,
    cookie_status: p.cookie_status === 'valid' ? 'valid' : p.cookie_status === 'expired' ? 'expired' : 'unknown',
    message: p.cookie_status === 'valid' ? 'Cookie 有效' : p.cookie_status === 'expired' ? 'Cookie 已过期，请刷新' : '未检测',
  }))
}

// ── 私信触发词 ─────────────────────────────────────────────────────────────

export async function GetDMKeywords() {
  await delay()
  return MOCK_DM_KEYWORDS
}

export async function AddDMKeyword(rule) { await delay(); return null }
export async function UpdateDMKeyword(rule) { await delay(); return null }
export async function DeleteDMKeyword(id) { await delay(); return null }

// ── 私信审核 ───────────────────────────────────────────────────────────────

export async function GetPendingReviews(page = 1, pageSize = 9) {
  await delay()
  return paged(MOCK_TASKS_REVIEW, page, pageSize)
}

export async function ApproveDMTasks(taskIds) { await delay(500); return null }
export async function SkipDMTasks(taskIds) { await delay(500); return null }

export async function ExportPendingReviews(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/pending_reviews.${format}`
}

// ── 私信发送队列 ───────────────────────────────────────────────────────────

export async function GetDMTasks(status = '', page = 1, pageSize = 9) {
  await delay()
  const filtered = status ? MOCK_TASKS_QUEUE.filter(t => t.status === status) : MOCK_TASKS_QUEUE
  return paged(filtered, page, pageSize)
}

export async function StartDMEngine() { await delay(); return null }
export async function StopDMEngine() { await delay(); return null }

export async function GetDMStatus() {
  return { engine_running: true, today_success: 128, today_failed: 3, pending_review_count: 23 }
}

export async function GetDMConfig() {
  return {
    template_path: 'C:/Users/43841/Downloads/templates.txt',
    min_interval_sec: 60,
    max_interval_sec: 180,
    daily_limit_per_account: 100,
    daily_limit_total: 500,
    concurrency: 3,
    auto_add_to_monitor: true,
    new_video_only: false,
    full_send_mode: false,
  }
}

export async function SaveDMConfig(config) { await delay(); return null }

export async function ExportDMTasks(status, format) {
  await delay(800)
  return `C:/Users/43841/Downloads/dm_tasks.${format}`
}

// ── 私信发送日志 ───────────────────────────────────────────────────────────

export async function GetDMSendLogs(profileId = '', status = '', page = 1, pageSize = 11) {
  await delay()
  let filtered = MOCK_DM_SEND_LOGS
  if (profileId) filtered = filtered.filter(l => l.profile_id === profileId)
  if (status) filtered = filtered.filter(l => l.status === status)
  return paged(filtered, page, pageSize)
}

export async function ExportDMSendLogs(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/dm_send_logs.${format}`
}

// ── 系统配置 ───────────────────────────────────────────────────────────────

export async function CheckBitBrowserStatus() {
  await delay(500)
  return { online: false }
}

export async function CheckSigningServiceStatus() {
  await delay(500)
  return { online: false }
}

export async function RefreshCookieFromBitBrowser(browserId) {
  await delay(2000)
  return { browser_id: browserId, cookie_length: 8421, updated_at: new Date().toISOString() }
}

export async function GetSystemConfig() {
  return {
    bit_browser: { port: 54345, default_browser_id: '' },
    signing: { port: 9527 },
    global: { monitor_interval_sec: 60, max_retry: 3, auto_clean_days: 7, blacklist_threshold: 5, dingtalk_webhook: '' },
  }
}

export async function SaveBitBrowserConfig(config) { await delay(); return null }
export async function SaveGlobalConfig(config) { await delay(); return null }

// ── 日志 ───────────────────────────────────────────────────────────────────

export async function GetLogs(level = '', keyword = '', page = 1, pageSize = 11) {
  await delay()
  let filtered = MOCK_SYSTEM_LOGS
  if (level) filtered = filtered.filter(l => l.level === level)
  if (keyword) filtered = filtered.filter(l => l.message.includes(keyword))
  return paged(filtered, page, pageSize)
}

export async function ClearLogs() { await delay(); return null }

export async function ExportLogs(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/system_logs.${format}`
}

// ── 通用 ───────────────────────────────────────────────────────────────────

export async function ExportData(dataType, format, filters = {}) {
  await delay(800)
  return `C:/Users/43841/Downloads/${dataType}_${Date.now()}.${format}`
}
