// Mock Wails bindings for development — v2.2
// In production these are auto-generated by Wails from Go methods

const delay = (ms = 300) => new Promise(r => setTimeout(r, ms))

function paged(items, page, pageSize) {
  const start = (page - 1) * pageSize
  return { items: items.slice(start, start + pageSize), total: items.length, page, page_size: pageSize }
}

// ── Mock data (cleared — all empty for production use) ──────────────────────

// Browser windows managed by user in Settings
const MOCK_BROWSER_WINDOWS = []

const MOCK_PROFILES = []
const MOCK_VIDEOS = []
const MOCK_COMMENTS = []
const MOCK_DM_KEYWORDS = []
const MOCK_TASKS_REVIEW = []
const MOCK_TASKS_QUEUE = []
const MOCK_DM_SEND_LOGS = []
const MOCK_COLLECT_HISTORY = []
const MOCK_SEARCH_RESULTS = []
const MOCK_SYSTEM_LOGS = []

// ── 比特浏览器窗口管理 ───────────────────────────────────────────────────────

export async function GetBrowserWindows() {
  await delay()
  return MOCK_BROWSER_WINDOWS
}

export async function AddBrowserWindow(profileId, name) {
  await delay(800)
  const seq = MOCK_BROWSER_WINDOWS.length + 1
  MOCK_BROWSER_WINDOWS.push({
    id: profileId,
    name,
    seq,
    conn_status: 'connected',
    login_status: 'unknown',
    cookie_updated_at: '',
    enabled: true,
    created_at: new Date().toISOString(),
  })
  return null
}

export async function TestBrowserWindow(profileId) {
  await delay(1200)
  // Stub: always succeeds in dev mode
  // In production, pings BitBrowser API to verify window exists
  return { online: true }
}

export async function CheckWindowLogin(profileId) {
  await delay(1500)
  // Stub (POC): returns valid to simulate a logged-in window.
  // Production: CDP WS → read sessionid cookies → call Douyin IM user info API.
  const w = MOCK_BROWSER_WINDOWS.find(x => x.id === profileId)
  if (w) w.login_status = 'valid'
  return { status: 'valid', message: 'Cookie 检测通过（POC 模式）' }
}

export async function UpdateWindowName(profileId, name) {
  await delay(300)
  const w = MOCK_BROWSER_WINDOWS.find(x => x.id === profileId)
  if (w) w.name = name
  return null
}

export async function DeleteBrowserWindow(profileId) {
  await delay(300)
  const w = MOCK_BROWSER_WINDOWS.find(x => x.id === profileId)
  if (w) w.enabled = false
  return null
}

// ── 评论监控 ───────────────────────────────────────────────────────────────

export async function GetVideos(page = 1, pageSize = 8) {
  await delay()
  return paged(MOCK_VIDEOS, page, pageSize)
}

export async function AddVideo(url, profileId) {
  await delay(500)
  return null
}

export async function DeleteVideo(videoId) {
  await delay(300)
  return null
}

export async function StartMonitor() { await delay(); return null }
export async function StopMonitor() { await delay(); return null }

export async function GetMonitorStatus() {
  return { running: false, current_round: 0, new_comments_this_round: 0, total_comments: 0 }
}

export async function GetComments(videoId, page = 1, pageSize = 11) {
  await delay()
  return paged(MOCK_COMMENTS, page, pageSize)
}

export async function ExportVideos(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/videos_export.${format}`
}

export async function ExportComments(videoId, format) {
  await delay(800)
  return `C:/Users/43841/Downloads/comments_export.${format}`
}

// ── 视频采集 ───────────────────────────────────────────────────────────────

export async function SearchVideos(keyword, sortType, publishTime, duration, count) {
  await delay(1000)
  return MOCK_SEARCH_RESULTS.slice(0, count || 20)
}

export async function StartAutoCollect() { await delay(); return null }
export async function StopAutoCollect() { await delay(); return null }

export async function GetKeywords() {
  await delay()
  return []
}

export async function AddKeyword(config) { await delay(); return null }
export async function UpdateKeyword(config) { await delay(); return null }
export async function DeleteKeyword(id) { await delay(); return null }

export async function GetCollectHistory(page = 1, pageSize = 8) {
  await delay()
  return paged(MOCK_COLLECT_HISTORY, page, pageSize)
}

export async function GetAutoCollectStatus() {
  return { running: false, next_collect_in_sec: 0, current_round_videos: 0, total_monitored: 0 }
}

export async function ExportCollectHistory(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/collect_history.${format}`
}

// ── 私信账号（从窗口管理派生）──────────────────────────────────────────────

export async function GetAccounts(page = 1, pageSize = 6) {
  await delay()
  // Derive account list from browser windows for binding selectors
  const profiles = MOCK_BROWSER_WINDOWS
    .filter(w => w.enabled)
    .map(w => ({
      seq: w.seq,
      profile_id: w.id,
      display_name: w.name,
      douyin_uid: '',
      nickname: w.name,
      cookie_status: w.login_status === 'valid' ? 'valid' : w.login_status === 'expired' ? 'expired' : 'unknown',
      cookie_updated_at: w.cookie_updated_at,
      test_passed: w.conn_status === 'connected',
      enabled: w.enabled,
      daily_dm_sent: 0,
      daily_dm_limit: 100,
      consecutive_failures: 0,
    }))
  return paged(profiles, page, pageSize)
}

export async function AddAccount(profileId) { await delay(500); return null }
export async function DeleteAccount(profileId) { await delay(); return null }
export async function ExtractAccountInfo(profileId) { await delay(1500); return null }
export async function TestSendDM(profileId, targetUID) { await delay(2000); return null }

export async function LoginBitBrowserWindow(profileId) {
  await delay(500)
  return { ws: `ws://127.0.0.1:9222/${profileId}` }
}

export async function ExportAccounts(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/accounts.${format}`
}

export async function GetStartupCheckResult() {
  await delay(800)
  return MOCK_BROWSER_WINDOWS
    .filter(w => w.enabled)
    .map(w => ({
      seq: w.seq,
      profile_id: w.id,
      nickname: w.name,
      cookie_status: w.login_status === 'valid' ? 'valid' : w.login_status === 'expired' ? 'expired' : 'unknown',
      message: w.login_status === 'valid' ? 'Cookie 有效' : w.login_status === 'expired' ? 'Cookie 已过期，请刷新' : '未检测，请前往设置验证',
    }))
}

// ── 私信触发词 ─────────────────────────────────────────────────────────────

export async function GetDMKeywords() {
  await delay()
  return MOCK_DM_KEYWORDS
}

export async function AddDMKeyword(rule) { await delay(); return null }
export async function UpdateDMKeyword(rule) { await delay(); return null }
export async function DeleteDMKeyword(id) { await delay(); return null }

// ── 私信审核 ───────────────────────────────────────────────────────────────

export async function GetPendingReviews(page = 1, pageSize = 9) {
  await delay()
  return paged(MOCK_TASKS_REVIEW, page, pageSize)
}

export async function ApproveDMTasks(taskIds) { await delay(500); return null }
export async function SkipDMTasks(taskIds) { await delay(500); return null }

export async function ExportPendingReviews(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/pending_reviews.${format}`
}

// ── 私信发送队列 ───────────────────────────────────────────────────────────

export async function GetDMTasks(status = '', page = 1, pageSize = 9) {
  await delay()
  const filtered = status ? MOCK_TASKS_QUEUE.filter(t => t.status === status) : MOCK_TASKS_QUEUE
  return paged(filtered, page, pageSize)
}

export async function StartDMEngine() { await delay(); return null }
export async function StopDMEngine() { await delay(); return null }

export async function GetDMStatus() {
  return { engine_running: false, today_success: 0, today_failed: 0, pending_review_count: 0 }
}

export async function GetDMConfig() {
  return {
    template_path: '',
    min_interval_sec: 60,
    max_interval_sec: 180,
    daily_limit_per_account: 100,
    daily_limit_total: 500,
    concurrency: 3,
    auto_add_to_monitor: true,
    new_video_only: false,
    full_send_mode: false,
  }
}

export async function SaveDMConfig(config) { await delay(); return null }

export async function ExportDMTasks(status, format) {
  await delay(800)
  return `C:/Users/43841/Downloads/dm_tasks.${format}`
}

// ── 私信发送日志 ───────────────────────────────────────────────────────────

export async function GetDMSendLogs(profileId = '', status = '', page = 1, pageSize = 11) {
  await delay()
  let filtered = MOCK_DM_SEND_LOGS
  if (profileId) filtered = filtered.filter(l => l.profile_id === profileId)
  if (status) filtered = filtered.filter(l => l.status === status)
  return paged(filtered, page, pageSize)
}

export async function ExportDMSendLogs(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/dm_send_logs.${format}`
}

// ── 系统配置 ───────────────────────────────────────────────────────────────

export async function CheckBitBrowserStatus() {
  await delay(500)
  return { online: false }
}

export async function CheckSigningServiceStatus() {
  await delay(500)
  return { online: false }
}

export async function RefreshCookieFromBitBrowser(profileId) {
  await delay(2000)
  // Stub: in production, opens BitBrowser window, extracts Cookie via CDP
  // Returns login_invalid: true if session expired
  return { profile_id: profileId, cookie_length: 0, updated_at: new Date().toISOString(), login_invalid: false }
}

export async function GetSystemConfig() {
  return {
    bit_browser: { port: 54345 },
    signing: { port: 9527 },
    global: { monitor_interval_sec: 60, monitor_retry_count: 3, comment_auto_clean_days: 7, auto_blacklist_threshold: 5, dingtalk_webhook: '' },
  }
}

export async function SaveBitBrowserConfig(config) { await delay(); return null }
export async function SaveGlobalConfig(config) { await delay(); return null }

// ── 日志 ───────────────────────────────────────────────────────────────────

export async function GetLogs(level = '', keyword = '', page = 1, pageSize = 11) {
  await delay()
  let filtered = MOCK_SYSTEM_LOGS
  if (level) filtered = filtered.filter(l => l.level === level)
  if (keyword) filtered = filtered.filter(l => l.message.includes(keyword))
  return paged(filtered, page, pageSize)
}

export async function ClearLogs() { await delay(); return null }

export async function ExportLogs(format) {
  await delay(800)
  return `C:/Users/43841/Downloads/system_logs.${format}`
}

// ── 通用 ───────────────────────────────────────────────────────────────────

export async function ExportData(dataType, format, filters = {}) {
  await delay(800)
  return `C:/Users/43841/Downloads/${dataType}_${Date.now()}.${format}`
}
